version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:80
        environment:
            LANG: ja_JP.UTF-8
            TZ: Asia/Tokyo
            APP_ENVIRONMENT: development
        volumes:
            - app-data:/data
        networks:
            - almsnw
        depends_on:
            - db
        cap_add:
            - SYS_ADMIN
    db:
        image: postgres:latest
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/path/to/data
        environment:
            POSTGRES_USER: alms
            POSTGRES_PASSWORD: password
            POSTGRES_DB: alms_development
            TZ: Asia/Tokyo
        networks:
            - almsnw

networks:
    almsnw:
        driver: bridge

volumes:
    app-data:
        driver: local
    postgres-data:
        driver: local
