version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        environment:
            LANG: ja_JP.UTF-8
            TZ: Asia/Tokyo
            ASPNETCORE_ENVIRONMENT: Development
            APP_URL: http://localhost:8080

        volumes:
            - app-data:/data
        networks:
            - almsnw
        depends_on:
            - db
        cap_add:
            - SYS_ADMIN
    db:
        image: postgres:latest
        ports:
            - '5432:5432'
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: alms
            POSTGRES_PASSWORD: password
            POSTGRES_DB: alms
            TZ: Asia/Tokyo
        networks:
            - almsnw

networks:
    almsnw:
        driver: bridge

volumes:
    app-data:
        driver: local
    db-data:
        driver: local
