version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.production
        volumes:
            #- ./production-app-data:/data
            - app-data:/data
            - ./keys/server.pfx:/server.pfx
            - ~/.aspnet/https:/root/.aspnet/https:ro
            - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
        environment:
            LANG: ja_JP.UTF-8
            TZ: Asia/Tokyo
            ASPNETCORE_ENVIRONMENT: Production
            ASPNETCORE_Kestrel__Certificates__Default__Password: password
            ASPNETCORE_Kestrel__Certificates__Default__Path: /server.pfx
            # Edit the following variables to suit your environment
            # SUB_DIR: "/alms"
            # LDAP_HOST: uni-ldap1.db.tokushima-u.ac.jp
            # LDAP_PORT: 636
            # LDAP_BASE: dc=tokushima-u,dc=ac,dc=jp
            # LDAP_ID_ATTR: uid
            # LDAP_MAIL_ATTR: mail
            # LDAP_NAME_ATTR: displayName;lang-ja
        networks:
            - alms
        depends_on:
            - db
        cap_add:
            - SYS_ADMIN
     
    db:
        image: postgres:latest
        ports:
            - 5432:5432
        volumes:
            #- ./production-db-data:/var/lib/postgresql/data
            - db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: alms
            POSTGRES_PASSWORD: password
            POSTGRES_DB: alms
            TZ: Asia/Tokyo
        networks:
            - alms

networks:
    alms:
        driver: bridge
volumes:
    app-data:
        driver: local
    db-data:
        driver: local
